### ISSUE TITLE
Week 2 Classy Functions

### ISSUE THREAD

**Issue by Rebecca-123** [VidhiKulkarni/teamlace#17]
Scrum Team GitHub pages (2 points)
- [x] Project Owner / Sponsor presentation
   - [x] results of review
   - [x] PII concerns
   - [x] hosting plan
   - [x] software license
- [x] 1st Code in GitHub with software license per 5.5

Individual GitHub pages (3 points)
- [x] GitHub page that documents key learnings and code snippets using GitHub and replit (See Challenges at the bottom of  [TT2 (Links to an external site.)](https://github.com/nighthawkcoders/nighthawk_csp/wiki/Tri-3-TT2-Python-Classes) for details)
- [x] Organize files, directories and menus for the first 3 weeks. 
- [x] Write Factorial function using classes, providing implementation of call.
- [x] Select your own Math function. Write it in Imperative and OOP form. 
- [x] Extra Credit.  Write Palindrome function using classes, must provide implementation of call.  Must indicate where error occurs on front and back comparison.

**Comment by Rebecca-123** [comment]
Feedback:
- Include contact info
- Events on calendar - email notifications?

**Comment by Rebecca-123** [comment]
Feedback:
- Include contact info
- Events on calendar - email notifications?

**Comment by VidhiKulkarni** [comment]
- Contact Club Page
- Link to Instagram
- Link to Discord
- Notify users of events

**Comment by shreya-ahujaa** [comment]
## Feedback from Crossover 

- Contact Us Page
     - Link to Discord 
- Area of Website that was Accessible on Every Page (Footer with Contact Information)
- Event: Embedded Google Calendar
    - Admins can Edit 
    - Email Notifications for Upcoming Events
    - Remind App Notifications
- Include Online Registration Form
