### ISSUE TITLE
Rebecca Su Week 1 Review

### ISSUE THREAD

**Issue by Rebecca-123** [VidhiKulkarni/teamlace#19]
**Total Score: 5/5**

Checks: 11/11
Individual Score: 3/3
Team Score: 2/2
Grader: Pranavi Inukurti

**Individual GitHub pages**
GitHub page for Test Prep study, requiring 5.3, 5.4 notes and actions( See "GitHub pages actions" at the bottom of each TPT page on [cspcoders](https://cspcoders.nighthawkcodingsociety.com/)).

- [x] 1- One Check 5.3
- [x] 1- One Check 5.4

**GitHub page that documents key learnings and code snippets using GitHub and replit.**
InfoDB lists
- [x] 1 - One Check for New Data, minimum of 4 items
InfoDB loops
- [x] 1- One Check For Loop running and sensible output
- [x] 1- One Check While Loop running and sensible output
- [x] 1- One Check Recursion running and sensible output
Fibonacci - (For Fibonacci(n) print complete list 0 - n and not just the nth term)
- [x] 4- Four checks: Algorithm, code with comments, Prints result, Prints Complete List,
- [x] 1- One check: comments and documentation throughout

**Comment by PranaviInukurti** [comment]
Individual Score: 3/3
Total Score: 11/11

- great runtime for code
- organized github page
