### ISSUE TITLE
Week 2 Individual Review - Rebecca Su

### ISSUE THREAD

**Issue by Rebecca-123** [VidhiKulkarni/teamlace#23]
Total Score: 6/5
Team Score: 2/2
Individual Score: 4/3
Grader: Pranavi Inukurti
[GitHub Page](https://rebecca-123.github.io/rebecca-tri-3/)

- [x] Organize files, directories and menus for the first 3 weeks.
- [x] Write Factorial function using classes, providing implementation of call.
- [x] Select your own Math function. Write it in Imperative and OOP form.
- [x] Extra Credit(1 point). Write Palindrome function using classes, must provide implementation of call. Must indicate where error occurs on front and back comparison.

**Comment by PranaviInukurti** [comment]
Team Score: 2/2 
- had good planning
- nice collaboration with the client and their needs

Individual Score: 4/3
- had all code with the specific requirements also
- had runtime on repl
- completed the palindrome function with classes and implementation of call
