### ISSUE TITLE
Week 2 Individual Review Ticket

### ISSUE THREAD

**Issue by VidhiKulkarni** [VidhiKulkarni/teamlace#24]
**Scrum Team GitHub pages 2/2**

- [x] Project Owner / Sponsor presentation(visuals like wireframes or HTML pages), results of review, PII concerns, hosting plan, and software license

- [x] 1st Code in GitHub with software license per 5.5

**Individual GitHub pages 3/3**

- [x] Organize files, directories and menus for the first 3 weeks. 

- [x] Write Factorial function using classes, providing implementation of call.

- [x] Select your own Math function. Write it in Imperative and OOP form.

**Comment by gigiguan** [comment]
Team: 2/2
Has license.
Good presentation. The wireframe looks great.

Individual: 3/3
- Has github action questions answered 5.5-5.6 
- Organized files in week 0, 1, 2 folders
- Wrote factorial function using classes and it is running
- For her own math function, she did a factors function (imperative)). She has testing values and outputs of test data. Has a factor class (OOP).
