### ISSUE TITLE
Week 2 Review Ticket - William Li

### ISSUE THREAD

**Issue by 3ghin5** [VidhiKulkarni/teamlace#25]
### Scrum Team GitHub pages (2 points)

- [ ] Project Owner / Sponsor presentation(visuals like wireframes or HTML pages), results of review, PII concerns, hosting plan, and software license

- [ ] 1st Code in GitHub with software license per 5.5

### Individual GitHub pages (3 points)

- [ ] [GitHub page](https://3ghin5.github.io/hatelace/dataStructures.html) that documents key learnings and code snippets using GitHub and replit
- [ ] Organize files, directories and menus for the first 3 weeks. 
- [ ] Write Factorial function using classes, providing implementation of call.
- [ ] Select your own Math function. Write it in Imperative and OOP form. 
 * Extra Credit(1 point).  Write Palindrome function using classes, must provide implementation of call.  Must indicate where error occurs on front and back comparison.

**Comment by cwang999** [comment]
- [ ] Project Owner / Sponsor presentation(visuals like wireframes or HTML pages), results of review, PII concerns, hosting plan, and software license
- [ ] 1st Code in GitHub with software license per 5.5
### Individual GitHub pages (3 points)
- [ ] [GitHub page](https://3ghin5.github.io/hatelace/dataStructures.html) that documents key learnings and code snippets using GitHub and replit
- [ ] Organize files, directories and menus for the first 3 weeks.
- [ ] Write Factorial function using classes, providing implementation of call.
- [ ] Select your own Math function. Write it in Imperative and OOP form.
 * Extra Credit(1 point).  Write Palindrome function using classes, must provide implementation of call.  Must indicate where error occurs on front and back comparison.
