### ISSUE TITLE
Vidhi Kulkarni - Algorithmic Final

### ISSUE THREAD

**Issue by VidhiKulkarni** [VidhiKulkarni/teamlace#26]
**Overall Score (graded by Abigail): 10/10
Overall Score (graded by William): 9.8/10
Twitter Video Score: 9.9/10**

[Link to Video](https://youtu.be/VXfRYxWLgFc)
[Github Pages](https://vidhikulkarni.github.io/individualrepo/)
[Replit]( https://replit.com/@vidhik/individualrepo-1)

Individual Coding:

- [x] GitHub Pages showing key learnings and challenges conquered from Tech Talks

- [x] GitHub commits you have made, show GitHub insights into your code commits.

- [x] Show Code running on Replit as well as IntelliJ

- [x] Menu review illustrating use of Lists and navigation: show runtime, code organization, code and comments

- [x] List and Loops: show runtime, code organization, code and comments

- [x] Class review and understanding: show runtime, code organization, code and comments

- [x] Show Crossover contribution:  Highlight work you did in crossover project: show their Replit runtime, code commit(s) in their GitHub repo

- [x] Show anything you have done to enhance what you have learned from Python code

**Comment by Abigail-Peltz** [comment]
[https://www.youtube.com/watch?v=VXfRYxWLgFc] (link to video)
Github Pages: [https://vidhikulkarni.github.io/individualrepo/]
Replit [https://replit.com/@vidhik/individualrepo-1]

10/10, all the work was clearly organized and complete, and it was easy to see the overall project. The video was clean and simple, and definitely checks off all of the criteria.

Additionally, the end of the video included bonus work, which is why the project deserves full marks.

**Comment by 3ghin5** [comment]
Quality of work

Share link(s) on slack to final work:  [GitHub pages](https://3ghin5.github.io/hatelace/), [Replit](https://replit.com/@3ghin5/hatelace#.replit), Review Ticket(s), TimeBox, or other methods you have used to organize work.
Coding Review

Individual Coding:

- [ ] GitHub Pages showing key learnings and challenges conquered from Tech Talks

- [ ] GitHub commits you have made, show GitHub insights into your code commits.

- [ ] Show Code running on Replit as well as IntelliJ

- [ ] Menu review illustrating use of Lists and navigation: show runtime, code organization, code and comments

- [ ] List and Loops: show runtime, code organization, code and comments

- [ ] Class review and understanding: show runtime, code organization, code and comments

- [ ] Show Crossover contribution:  Highlight work you did in crossover project: show their Replit runtime, code commit(s) in their GitHub repo. Show anything you have done to enhance what you have learned from Python code

Video 2 minutes: showing the above, quality suggested as follows

- [ ] Make sure you cover everything, but create your own order and optimize time

- [ ] Use Voice or Captions.   Try not to wiggle mouse a lot or over scroll.  Make sure you have a clear plan before you start.

- [ ] Perform video in small parts 15-30 seconds and finish a key subject.  Then put the final Video together with Video editing or Youtube playlists.

**Comment by 3ghin5** [comment]
Graded by William Li
9.8/10
-0.2 Video was noticeably sped up, time could've been optimized better. Other than that everything was present.
