### ISSUE TITLE
Vidhi Kulkarni - Accounts and Logins

### ISSUE THREAD

**Issue by VidhiKulkarni** [VidhiKulkarni/teamlace#28]
**Score by Reinhardt and Valerie: 5/5**
- [x] [Hack 1: Add Phone Number to Sign Up / Authorization screen](https://github.com/VidhiKulkarni/nighthawk_csp/commit/37ae8e94e7ab3e2760ae3a9b355165ed7dd63105)
- [x] [Hack 2: Add logout to CRUD screen](https://github.com/VidhiKulkarni/nighthawk_csp/commit/7b0fcffd4daeb918c7ff6b011307ebd0cc818b0c)
- [x] [Hack 3: Add login_required to another portion of the project -- All Commits from April 17](https://github.com/VidhiKulkarni/nighthawk_csp/commits/master)
- [x] [CB Create Task Coding requirements documented](https://github.com/arushi10/codefish/wiki/Vidhi---Written-Create-Task)
- [x] [Runtime of Code(with comments) on Replit/Intellij](https://replit.com/@vidhik/CreateTask#index.html)

**Comment by Reinhardtlotter** [comment]
Reinhardt And Valerie comment: 5/5 very good work shown. Ready to develop PBL and submit Create Task. TicTacToe was a clever idea and implementation. Hacks were done efficiently and worked.
