### ISSUE TITLE
Week 0 Rebecca Su Review

### ISSUE THREAD

**Issue by Rebecca-123** [VidhiKulkarni/teamlace#3]
[GitHub Page](https://rebecca-123.github.io/rebecca-tri-3/)

Crossover Grade: 2.75/3

- [x] Test Prep
- [x] Create Task
- [x] Data Structures

**Comment by PranaviInukurti** [comment]
Total Score: 2.75/3
Had TPT Github Page, Create Task, and Data Structures but couldn't show runtime on Replit, had to use Intellij
