### ISSUE TITLE
Vidhi Kulkarni - Review Ticket (Proctored MCQ Week1 : Quiz1, Quiz2 Scores)

### ISSUE THREAD

**Issue by VidhiKulkarni** [VidhiKulkarni/teamlace#33]
- [ ] [Finals-Quiz1 score/50 and corrections](https://vidhikulkarni.github.io/individualrepo/corrections)

- [ ] [Finals-Quiz2 score/50 and corrections](https://vidhikulkarni.github.io/individualrepo/corrections)

- [ ] [Create Task code/runtime and 1 min video](https://youtu.be/Xy_F5jf8m5w)

**Comment by ValenReynolds** [comment]
Score 5/5
- [ ] [Finals-Quiz1 score/50 and corrections](https://vidhikulkarni.github.io/individualrepo/corrections)

 

- [ ] [Finals-Quiz2 score/50 and corrections](https://vidhikulkarni.github.io/individualrepo/corrections)

- [ ]  [Create Task code/runtime and 1 min video](https://youtu.be/Xy_F5jf8m5w)
