### ISSUE TITLE
Vidhi Kulkarni - Proctored MCQ Week2 : Quiz3 and Create Task review

### ISSUE THREAD

**Issue by VidhiKulkarni** [VidhiKulkarni/teamlace#34]
[Jekyll Pages](https://vidhikulkarni.github.io/individualrepo/)

- [x] [GH Indi Page](https://vidhikulkarni.github.io/individualrepo/), [Review Ticket](https://github.com/VidhiKulkarni/teamlace/issues/34), [Crossover graded](), [Study Plan](https://vidhikulkarni.github.io/individualrepo/studyplan)

- [x] [Create Task and Create Task Crossover Review comments (completed by Thu)](https://vidhikulkarni.github.io/individualrepo/createtask)

- [x] [Quiz3 MCQ results and test corrections](https://vidhikulkarni.github.io/individualrepo/quiz3corrections)

**Comment by Reinhardtlotter** [comment]
4.5/5 Quiz score is above needed. Corrections have adequate effort. Create task review was done with me so I know that it was done but no comments from the review.
