### ISSUE TITLE
Week 1 Rebecca Su Individual Review Ticket

### ISSUE THREAD

**Issue by Rebecca-123** [VidhiKulkarni/teamlace#39]
**Score: 1.8/2**

- [x] Minimum of 5 hours of Code, Code, Code; 4 hours can easily be performed in class
- [x] A personally developed Review Ticket with Tangibles
- [x] Tangibles that easily help individuals visualize work in project, honest contributions!
- [x] In ticket, review comments with Scrum Team crossover and Scrum Master
- [x] Score of 2 points, 1.8 maximum
- [x] Meeting 5 hours with commit evidence is minumum for .9
- [x] Meeting team and sponsor objectives

Tangibles/Progress
Issues:
1. [Home Page](https://github.com/VidhiKulkarni/teamlace/issues/7)
2. [Database](https://github.com/VidhiKulkarni/teamlace/issues/38)

- [x] Customized database according to sponsor objectives (changed original Nighthawk Coding Society database - new columns and ensure CRUD still functional)
- [x] Technical requirement: notes page for individual users
- Future tasks:
   - [ ] Update
   - [ ] Delete 
- [x] [Commits](https://github.com/VidhiKulkarni/teamlace/commits?author=Rebecca-123)
- [x] Updated navbar according to [wireframe/sponsor objectives](https://www.canva.com/design/DAE7RRwpQjw/view?embed#4)
- [x] Home Page
   - [x] Gallery
- Future tasks:
   - [ ] Basic Description

**Comment by Rebecca-123** [comment]
https://github.com/VidhiKulkarni/teamlace/issues/47#issuecomment-1130586881

**Comment by shreya-ahujaa** [comment]
## Individual Score: 1.8/2

- [x] The Tangibles show that there was a good amount of effort put into the team project and there was around 5 hours of work to support that
- [x] Clear Organization in Review Ticket throughout the week
- [x] There are a lot of commits that show that there was work being done over the week
- [x] The Database is working well and it shows that it has all the requirements done
- [x] The Home Page also has a changing image carousel, with things relating to the website, which all takes time and shows progress and work
