### ISSUE TITLE
Week 0 Review Ticket: Vidhi Kulkarni

### ISSUE THREAD

**Issue by VidhiKulkarni** [VidhiKulkarni/teamlace#5]
- [x] GitHub page for Test Prep study, requiring 5.1, 5.2 notes and actions
- [x] GitHub page that documents Data Structures project, using code snippets for key learnings, and links to  GitHub for code and Replit for runtime
- [x] GitHub page that documents intended Create Task project for College Board, snippets, and links to Runtime

**Comment by ValenReynolds** [comment]
Overall Score: 3/3
GitHub page for Test Prep study, requiring 5.1, 5.2 notes and actions completed (1/1)
GitHub page that documents Data Structures project with running Replit and links to code on Github (1/1)
GitHub page that documents intended Create Task project for College Board, snippets, and links to Runtime completed (1/1)
Everything is on Jekyll
